/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1D7o85zxkBd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"

export default function Home() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="hidden w-64 border-r bg-gray-100 dark:border-gray-800 dark:bg-gray-900 lg:block">
        <div className="flex h-full flex-col gap-4 p-4">
          <div className="flex items-center gap-2">
            <Package2Icon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
            <h3 className="text-lg font-semibold">FAQ</h3>
          </div>
          <nav className="flex flex-col gap-1">
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              General
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              Installation Guides
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              Running SimAI
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              Troubleshooting
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              Rules and Policies
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              Donation
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              FLOPS
            </Link>
            <Link
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
              href="#"
            >
              Miscellaneous
            </Link>
          </nav>
        </div>
      </div>
      <div className="flex-1 p-4 md:p-6 lg:p-8">
        <div className="mx-auto max-w-4xl">
          <div className="grid gap-8 lg:grid-cols-2">
            <div>
              <h1 className="text-3xl font-bold tracking-tight md:text-4xl">Frequently Asked Questions</h1>
              <p className="mt-4 text-gray-500 dark:text-gray-400">
                You'll find a large library of frequently asked questions about all things connected to the ResearchAI
                organization and the SimAI software. This section contains everything from guides and information about
                how to install and use the SimAI software to the science behind our research. Look through the sidebar
                and find the topic you want to know more about.
              </p>
            </div>
            <div className="flex items-center justify-center">
              <img
                alt="FAQ"
                className="rounded-lg"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
          </div>
          <div className="mt-12 space-y-8">
            <Accordion collapsible type="single">
              <AccordionItem value="general">
                <AccordionTrigger className="text-lg font-semibold">General</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold">What is the ResearchAI organization?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        ResearchAI is a non-profit organization dedicated to advancing the field of artificial
                        intelligence through research and development. We work on a variety of projects aimed at pushing
                        the boundaries of what's possible with AI.
                      </p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold">What is the SimAI software?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        SimAI is a powerful simulation software developed by ResearchAI. It allows researchers and
                        developers to create complex AI models and test them in a variety of environments. SimAI is used
                        by our team and the broader AI community to advance the state of the art in AI research.
                      </p>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="installation">
                <AccordionTrigger className="text-lg font-semibold">Installation Guides</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold">How do I install SimAI on my computer?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">To install SimAI, follow these steps:</p>
                      <ol className="mt-2 list-decimal space-y-2 pl-4 text-gray-500 dark:text-gray-400">
                        <li>Download the latest version of SimAI from our website.</li>
                        <li>Run the installer and follow the on-screen instructions to complete the installation.</li>
                        <li>Once installed, you can launch SimAI from the Start menu or your desktop.</li>
                      </ol>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold">What are the system requirements for running SimAI?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        SimAI has the following minimum system requirements:
                      </p>
                      <ul className="mt-2 list-disc space-y-2 pl-4 text-gray-500 dark:text-gray-400">
                        <li>Windows 10 or later</li>
                        <li>Intel Core i5 or AMD Ryzen 5 processor</li>
                        <li>8GB of RAM</li>
                        <li>NVIDIA GeForce GTX 1060 or AMD Radeon RX 580 graphics card</li>
                        <li>50GB of available storage space</li>
                      </ul>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="running">
                <AccordionTrigger className="text-lg font-semibold">Running SimAI</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold">How do I create a new simulation in SimAI?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        To create a new simulation in SimAI, follow these steps:
                      </p>
                      <ol className="mt-2 list-decimal space-y-2 pl-4 text-gray-500 dark:text-gray-400">
                        <li>Launch SimAI and click on the "New Simulation" button in the main menu.</li>
                        <li>
                          Select the type of simulation you want to create (e.g., reinforcement learning, computer
                          vision, natural language processing).
                        </li>
                        <li>Configure the simulation settings, such as the environment, agents, and objectives.</li>
                        <li>Click the "Start Simulation" button to begin running the simulation.</li>
                      </ol>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold">How do I analyze the results of a simulation?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        SimAI provides a variety of tools and visualizations to help you analyze the results of your
                        simulations. You can access these tools by clicking on the "Analyze" button after a simulation
                        has completed. From there, you can view:
                      </p>
                      <ul className="mt-2 list-disc space-y-2 pl-4 text-gray-500 dark:text-gray-400">
                        <li>Performance metrics and statistics</li>
                        <li>Visualizations of agent behavior and environment</li>
                        <li>Detailed logs and data exports</li>
                      </ul>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="troubleshooting">
                <AccordionTrigger className="text-lg font-semibold">Troubleshooting</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold">Why is my simulation running slowly?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        There are a few common reasons why a simulation might be running slowly in SimAI:
                      </p>
                      <ul className="mt-2 list-disc space-y-2 pl-4 text-gray-500 dark:text-gray-400">
                        <li>Your computer hardware doesn't meet the minimum system requirements.</li>
                        <li>The simulation is too complex or has too many agents and objects.</li>
                        <li>There are issues with the simulation configuration or environment.</li>
                      </ul>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        If you're experiencing performance issues, try reducing the complexity of your simulation or
                        upgrading your computer hardware. You can also reach out to our support team for further
                        troubleshooting assistance.
                      </p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold">
                        I'm getting an error when trying to run SimAI. What should I do?
                      </h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        If you're encountering an error when trying to run SimAI, here are some steps you can take:
                      </p>
                      <ol className="mt-2 list-decimal space-y-2 pl-4 text-gray-500 dark:text-gray-400">
                        <li>Check the error message and try to identify the root cause of the issue.</li>
                        <li>Ensure that your computer meets the minimum system requirements for running SimAI.</li>
                        <li>Try reinstalling SimAI to see if that resolves the problem.</li>
                        <li>If the issue persists, reach out to our support team for further assistance.</li>
                      </ol>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="rules">
                <AccordionTrigger className="text-lg font-semibold">Rules and Policies</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold">What are the terms of use for SimAI?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        SimAI is provided for non-commercial research and educational purposes only. Users are not
                        permitted to modify, distribute, or create derivative works based on SimAI without prior written
                        permission from ResearchAI. Additionally, users must agree to our terms of service and privacy
                        policy before using the software.
                      </p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold">Can I use SimAI for commercial purposes?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        No, SimAI is not licensed for commercial use. If you would like to use SimAI for commercial
                        purposes, please contact our sales team to discuss licensing options.
                      </p>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="donation">
                <AccordionTrigger className="text-lg font-semibold">Donation</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold">How can I support ResearchAI?</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400" />
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </div>
    </div>
  )
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}
