/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rDCnwqc3S7I
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function Home() {
  return (
    <main className="flex flex-col">
      <section className="w-full bg-gray-100 py-20 dark:bg-gray-800">
        <div className="container mx-auto flex flex-col items-center justify-center gap-6 px-4 md:px-6">
          <div className="flex flex-col items-center gap-4">
            <img
              alt="ResearchAI Logo"
              className="h-16 w-16"
              height={64}
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width={64}
            />
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">ResearchAI</h1>
          </div>
          <p className="max-w-[600px] text-center text-gray-500 dark:text-gray-400 md:text-xl">
            Pioneering the future of artificial intelligence through innovative research and cutting-edge software
            solutions.
          </p>
        </div>
      </section>
      <section className="w-full py-20 md:py-24 lg:py-32">
        <div className="container mx-auto grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About ResearchAI</h2>
            <p className="text-gray-500 dark:text-gray-400 md:text-xl">
              ResearchAI is a leading research organization dedicated to advancing the field of artificial intelligence.
              Our mission is to push the boundaries of what's possible with AI, exploring new frontiers and developing
              innovative solutions that transform industries and improve lives.
            </p>
            <p className="text-gray-500 dark:text-gray-400 md:text-xl">
              At the heart of our work is a deep commitment to ethical and responsible AI development. We believe that
              AI should be designed to benefit humanity, and we strive to ensure that our research and technologies
              adhere to the highest standards of safety, transparency, and accountability.
            </p>
          </div>
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              SimAI: Our Flagship Software
            </h2>
            <p className="text-gray-500 dark:text-gray-400 md:text-xl">
              SimAI is our cutting-edge software platform that enables researchers, developers, and businesses to
              harness the power of AI in their applications. With its advanced simulation capabilities, intuitive user
              interface, and robust set of features, SimAI empowers users to experiment, test, and deploy AI-driven
              solutions with ease.
            </p>
            <p className="text-gray-500 dark:text-gray-400 md:text-xl">
              Whether you're exploring new AI algorithms, training machine learning models, or integrating AI into your
              existing products, SimAI provides the tools and resources you need to succeed. Experience the future of AI
              with ResearchAI and SimAI.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full bg-gray-100 py-20 dark:bg-gray-800">
        <div className="container mx-auto space-y-10 px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet the Team</h2>
            <p className="max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl">
              The brilliant minds behind ResearchAI's groundbreaking work.
            </p>
          </div>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <div className="flex flex-col items-center gap-4">
              <Avatar>
                <AvatarImage alt="John Doe" src="/team-member-1.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="space-y-1 text-center">
                <h3 className="text-lg font-semibold">John Doe</h3>
                <p className="text-gray-500 dark:text-gray-400">Co-Founder, CEO</p>
                <div className="flex gap-2 justify-center">
                  <Link href="#" target="_blank">
                    <TwitterIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <LinkedinIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <FacebookIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-4">
              <Avatar>
                <AvatarImage alt="Jane Smith" src="/team-member-2.jpg" />
                <AvatarFallback>JS</AvatarFallback>
              </Avatar>
              <div className="space-y-1 text-center">
                <h3 className="text-lg font-semibold">Jane Smith</h3>
                <p className="text-gray-500 dark:text-gray-400">Chief Research Officer</p>
                <div className="flex gap-2 justify-center">
                  <Link href="#" target="_blank">
                    <TwitterIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <LinkedinIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <FacebookIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-4">
              <Avatar>
                <AvatarImage alt="Michael Johnson" src="/team-member-3.jpg" />
                <AvatarFallback>MJ</AvatarFallback>
              </Avatar>
              <div className="space-y-1 text-center">
                <h3 className="text-lg font-semibold">Michael Johnson</h3>
                <p className="text-gray-500 dark:text-gray-400">Lead Software Engineer</p>
                <div className="flex gap-2 justify-center">
                  <Link href="#" target="_blank">
                    <TwitterIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <LinkedinIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <FacebookIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-4">
              <Avatar>
                <AvatarImage alt="Emily Davis" src="/team-member-4.jpg" />
                <AvatarFallback>ED</AvatarFallback>
              </Avatar>
              <div className="space-y-1 text-center">
                <h3 className="text-lg font-semibold">Emily Davis</h3>
                <p className="text-gray-500 dark:text-gray-400">Machine Learning Scientist</p>
                <div className="flex gap-2 justify-center">
                  <Link href="#" target="_blank">
                    <TwitterIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <LinkedinIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                  <Link href="#" target="_blank">
                    <FacebookIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-20 md:py-24 lg:py-32">
        <div className="container mx-auto grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
            <p className="text-gray-500 dark:text-gray-400 md:text-xl">
              Have a question, feedback, or interested in collaborating? We'd love to hear from you.
            </p>
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <MailboxIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <a className="text-gray-500 hover:underline dark:text-gray-400" href="#">
                  info@researchai.com
                </a>
              </div>
              <div className="flex items-center gap-2">
                <PhoneIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <a className="text-gray-500 hover:underline dark:text-gray-400" href="#">
                  +1 (555) 123-4567
                </a>
              </div>
            </div>
            <div className="flex gap-4">
              <Link href="#" target="_blank">
                <TwitterIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
              </Link>
              <Link href="#" target="_blank">
                <LinkedinIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
              </Link>
              <Link href="#" target="_blank">
                <FacebookIcon className="h-6 w-6 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" />
              </Link>
            </div>
          </div>
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Join the AI Revolution</h2>
            <p className="text-gray-500 dark:text-gray-400 md:text-xl">
              Discover how ResearchAI and SimAI can transform your business or research project. Get in touch to learn
              more.
            </p>
            <Button variant="default">Contact Us</Button>
          </div>
        </div>
      </section>
    </main>
  )
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailboxIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
