/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EgHGaU3hsOT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, Card } from "@/components/ui/card"

export default function Home() {
  return (
    <>
      <header className="bg-gray-900 py-6 px-4 md:px-6">
        <h1 className="text-2xl font-bold text-white">AI Research Projects</h1>
      </header>
      <main className="bg-gray-100 dark:bg-gray-800 py-12 px-4 md:px-6">
        <section className="max-w-6xl mx-auto space-y-8">
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Current Projects</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Project A</CardTitle>
                  <CardDescription>Start Date: 03/15/2023</CardDescription>
                  <CardDescription>End Date: present</CardDescription>
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Project B</CardTitle>
                  <CardDescription>Start Date: 06/01/2022</CardDescription>
                  <CardDescription>End Date: present</CardDescription>
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Project C</CardTitle>
                  <CardDescription>Start Date: 09/20/2023</CardDescription>
                  <CardDescription>End Date: present</CardDescription>
                </CardHeader>
              </Card>
            </div>
          </div>
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-4">Finished Projects</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Project X</CardTitle>
                  <CardDescription>Start Date: 01/01/2022</CardDescription>
                  <CardDescription>End Date: 12/31/2022</CardDescription>
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Project Y</CardTitle>
                  <CardDescription>Start Date: 04/15/2021</CardDescription>
                  <CardDescription>End Date: 09/30/2022</CardDescription>
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Project Z</CardTitle>
                  <CardDescription>Start Date: 07/01/2020</CardDescription>
                  <CardDescription>End Date: 06/30/2021</CardDescription>
                </CardHeader>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
