/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cFDq1sUWYAO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"

export function Common() {
  return (
    <nav className="bg-white px-6 py-4 shadow-sm">
      <div className="container mx-auto flex flex-wrap items-center justify-between">
        <div className="flex items-center space-x-6">
          <Link className="text-gray-700 font-semibold" href="/">
            AI Research Lab
          </Link>
          <div className="hidden space-x-4 md:flex">
            <Link className="text-gray-700 hover:text-gray-900" href="/join">
              Join
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/about">
              About
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/projects">
              Projects
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/results">
              Results
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/publications">
              Publications
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/FAQ">
              FAQ
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/donate">
              Donate
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/data">
              Data
            </Link>
            <Link className="text-gray-700 hover:text-gray-900" href="/statistics">
              Statistics
            </Link>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <button className="text-gray-700 hover:text-gray-900 transition-colors duration-300 ease-in-out">
            <MoonIcon className="h-6 w-6 animate-spin-slow" />
          </button>
          <button className="text-gray-700 hover:text-gray-900 md:ml-auto">
            <UserIcon className="h-6 w-6" />
          </button>
        </div>
      </div>
    </nav>
  )
}

export function CommonFooter() {
  return (
    <footer className="bg-black px-6 py-4">
      <div className="container mx-auto flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <MountainIcon className="h-6 w-6 text-white" />
          <span className="text-white">AI Research Lab</span>
        </div>
        <span className="text-sm text-white">© 2024 AI Research Lab. All rights reserved.</span>
      </div>
    </footer>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}

function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}

function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
