/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vAoQeTCJBl4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export default function Home() {
  return (
    <main className="flex flex-col w-full min-h-screen">
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center gap-6 px-4 md:px-6">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
              Explore Our AI-Generated Datasets
            </h1>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Discover a wealth of scientific data generated by our advanced AI models, spanning a wide range of
              disciplines.
            </p>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Explore Datasets
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800" id="datasets">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Discover Our AI-Generated Datasets
              </h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Browse through our extensive collection of AI-generated datasets across various scientific disciplines.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-6xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Biology Dataset</span>
              </Link>
              <img
                alt="Biology Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Biology Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Explore our AI-generated dataset on various biological phenomena, including cell structures, genetic
                  sequences, and more.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Chemistry Dataset</span>
              </Link>
              <img
                alt="Chemistry Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Chemistry Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Discover our AI-generated dataset on chemical compounds, reactions, and properties, perfect for
                  research and experimentation.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Physics Dataset</span>
              </Link>
              <img
                alt="Physics Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Physics Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Explore our AI-generated dataset on various physical phenomena, including mechanics, thermodynamics,
                  and electromagnetism.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Astronomy Dataset</span>
              </Link>
              <img
                alt="Astronomy Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Astronomy Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Discover our AI-generated dataset on celestial objects, astronomical phenomena, and the structure of
                  the universe.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Earth Science Dataset</span>
              </Link>
              <img
                alt="Earth Science Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Earth Science Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Explore our AI-generated dataset on Earth's geological processes, atmospheric phenomena, and
                  environmental data.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Materials Science Dataset</span>
              </Link>
              <img
                alt="Materials Science Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Materials Science Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Discover our AI-generated dataset on the properties and characteristics of various materials,
                  including metals, polymers, and ceramics.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Neuroscience Dataset</span>
              </Link>
              <img
                alt="Neuroscience Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Neuroscience Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Explore our AI-generated dataset on the structure and function of the human nervous system, including
                  brain imaging data and neural activity.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Ecology Dataset</span>
              </Link>
              <img
                alt="Ecology Dataset"
                className="object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="bg-white p-4 dark:bg-gray-950">
                <h3 className="font-semibold text-lg">Ecology Dataset</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                  Discover our AI-generated dataset on ecological systems, including data on species, habitats, and
                  environmental interactions.
                </p>
                <div className="mt-2">
                  <Link className="inline-flex items-center text-sm font-medium text-gray-900 hover:underline dark:text-gray-50" href="#">
                    Download
                    <ArrowRightIcon className="ml-1 h-4 w-4" />
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-4 mt-8 sm:flex-row sm:justify-between">
            <div className="flex items-center gap-2">
              <Input className="max-w-md flex-1 bg-white dark:bg-gray-950" placeholder="Search datasets" />
              <Button>Search</Button>
            </div>
            <div className="flex items-center gap-2">
              <Select defaultValue="all">
                <SelectTrigger className="w-48">
                  <SelectValue placeholder="Filter by discipline" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All</SelectItem>
                  <SelectItem value="biology">Biology</SelectItem>
                  <SelectItem value="chemistry">Chemistry</SelectItem>
                  <SelectItem value="physics">Physics</SelectItem>
                  <SelectItem value="astronomy">Astronomy</SelectItem>
                  <SelectItem value="earth-science">Earth Science</SelectItem>
                  <SelectItem value="materials-science">Materials Science</SelectItem>
                  <SelectItem value="neuroscience">Neuroscience</SelectItem>
                  <SelectItem value="ecology">Ecology</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
