/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QAsuZaeVdsc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"

export default function Home() {
  return (
    <div className="flex w-full max-w-6xl mx-auto">
      <div className="hidden lg:block w-64 mr-8">
        <div className="sticky top-6 space-y-6">
          <div>
            <h3 className="text-sm font-semibold mb-2">Filter by Topic</h3>
            <div className="space-y-2">
              <div className="flex items-center space-x-2">
                <Checkbox id="topic-biology" />
                <Label className="text-sm font-medium" htmlFor="topic-biology">
                  Biology
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox id="topic-chemistry" />
                <Label className="text-sm font-medium" htmlFor="topic-chemistry">
                  Chemistry
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox id="topic-physics" />
                <Label className="text-sm font-medium" htmlFor="topic-physics">
                  Physics
                </Label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex-1">
        <main className="w-full px-4 md:px-6 py-12 md:py-16">
          <header className="mb-8 md:mb-12">
            <div className="flex items-center justify-between mb-4">
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight">Publications</h1>
              <div className="w-full max-w-md">
                <Input className="w-full" placeholder="Search publications..." type="search" />
              </div>
            </div>
            <p className="text-gray-500 dark:text-gray-400 mt-2 max-w-[700px]">
              Explore the latest research papers published by our AI scientists across biology, chemistry, and physics.
            </p>
          </header>
          <div className="grid gap-8">
            <Link
              className="block bg-white rounded-lg shadow-sm dark:bg-gray-950 dark:border dark:border-gray-800 transition-all duration-300 hover:scale-[1.02]"
              href="#"
            >
              <div className="p-6 md:p-8">
                <div className="flex items-start justify-between mb-4">
                  <div className="space-y-2">
                    <h2 className="text-xl md:text-2xl font-semibold">
                      Optimizing Molecular Structures for Improved Catalytic Activity
                    </h2>
                    <p className="text-gray-500 dark:text-gray-400 text-sm">John Doe, Jane Smith, Michael Johnson</p>
                  </div>
                  <div className="flex items-center space-x-4">
                    <a
                      className="inline-flex items-center space-x-2 text-gray-900 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300 dark:text-gray-50"
                      href="#"
                    >
                      <FileIcon className="w-5 h-5" />
                      <span>PDF</span>
                    </a>
                    <a
                      className="inline-flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                      href="#"
                    >
                      <LinkIcon className="w-5 h-5" />
                      <span>DOI</span>
                    </a>
                  </div>
                </div>
                <p className="text-gray-700 dark:text-gray-300">
                  This paper presents a novel approach to optimizing molecular structures for improved catalytic
                  activity. The proposed method combines computational modeling, experimental validation, and machine
                  learning to systematically explore the design space and identify optimal molecular configurations. The
                  results demonstrate significant improvements in catalytic performance across a range of chemical
                  reactions, with potential applications in renewable energy, environmental remediation, and sustainable
                  manufacturing.
                </p>
                <div className="mt-6 text-sm text-gray-500 dark:text-gray-400">
                  <p>
                    Published in
                    <a
                      className="text-gray-900 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300 dark:text-gray-50"
                      href="#"
                    >
                      Journal of Catalysis
                    </a>
                    , Volume 123, Issue 4, April 2023.
                  </p>
                </div>
              </div>
            </Link>
            <Link
              className="block bg-white rounded-lg shadow-sm dark:bg-gray-950 dark:border dark:border-gray-800 transition-all duration-300 hover:scale-[1.02]"
              href="#"
            >
              <div className="p-6 md:p-8">
                <div className="flex items-start justify-between mb-4">
                  <div className="space-y-2">
                    <h2 className="text-xl md:text-2xl font-semibold">
                      Predicting Protein Folding Dynamics using Deep Learning
                    </h2>
                    <p className="text-gray-500 dark:text-gray-400 text-sm">Jane Doe, Michael Smith, John Johnson</p>
                  </div>
                  <div className="flex items-center space-x-4">
                    <a
                      className="inline-flex items-center space-x-2 text-gray-900 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300 dark:text-gray-50"
                      href="#"
                    >
                      <FileIcon className="w-5 h-5" />
                      <span>PDF</span>
                    </a>
                    <a
                      className="inline-flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                      href="#"
                    >
                      <LinkIcon className="w-5 h-5" />
                      <span>DOI</span>
                    </a>
                  </div>
                </div>
                <p className="text-gray-700 dark:text-gray-300">
                  This paper presents a novel deep learning-based approach for predicting protein folding dynamics. The
                  proposed model leverages large-scale molecular simulation data and advanced neural network
                  architectures to accurately forecast the complex conformational changes that occur during the folding
                  process. The results demonstrate significant improvements in prediction accuracy compared to
                  traditional computational methods, with potential applications in drug discovery, protein engineering,
                  and structural biology.
                </p>
                <div className="mt-6 text-sm text-gray-500 dark:text-gray-400">
                  <p>
                    Published in
                    <a
                      className="text-gray-900 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300 dark:text-gray-50"
                      href="#"
                    >
                      Biophysical Journal
                    </a>
                    , Volume 456, Issue 2, February 2023.
                  </p>
                </div>
              </div>
            </Link>
            <Link
              className="block bg-white rounded-lg shadow-sm dark:bg-gray-950 dark:border dark:border-gray-800 transition-all duration-300 hover:scale-[1.02]"
              href="#"
            >
              <div className="p-6 md:p-8">
                <div className="flex items-start justify-between mb-4">
                  <div className="space-y-2">
                    <h2 className="text-xl md:text-2xl font-semibold">
                      Quantum Simulation of Topological Phase Transitions
                    </h2>
                    <p className="text-gray-500 dark:text-gray-400 text-sm">Michael Lee, Sarah Chen, David Kim</p>
                  </div>
                  <div className="flex items-center space-x-4">
                    <a
                      className="inline-flex items-center space-x-2 text-gray-900 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300 dark:text-gray-50"
                      href="#"
                    >
                      <FileIcon className="w-5 h-5" />
                      <span>PDF</span>
                    </a>
                    <a
                      className="inline-flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                      href="#"
                    >
                      <LinkIcon className="w-5 h-5" />
                      <span>DOI</span>
                    </a>
                  </div>
                </div>
                <p className="text-gray-700 dark:text-gray-300">
                  This paper presents a novel quantum simulation approach for investigating topological phase
                  transitions in condensed matter systems. The proposed method combines advanced quantum algorithms,
                  high-performance computing, and machine learning to accurately model the complex many-body dynamics
                  underlying these phenomena. The results provide new insights into the fundamental physics of
                  topological materials and pave the way for the development of next-generation quantum technologies.
                </p>
                <div className="mt-6 text-sm text-gray-500 dark:text-gray-400">
                  <p>
                    Published in
                    <a
                      className="text-gray-900 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-300 dark:text-gray-50"
                      href="#"
                    >
                      Physical Review Letters
                    </a>
                    , Volume 789, Issue 3, March 2023.
                  </p>
                </div>
              </div>
            </Link>
          </div>
        </main>
      </div>
    </div>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}


function LinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}
